[package]
name = "hello-wasm"
version = "0.1.1"
authors = ["ch3n4y@gmail.com"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/ch3n4y/hello-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"